# Generated by Django 2.2.10 on 2020-02-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=3, verbose_name='Abbreviation name of the currency')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Exchange rate value')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_exchange_rate', to='currencies.Currency', verbose_name='Base currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_exchange_rate', to='currencies.Currency', verbose_name='Target currency')),
            ],
        ),
    ]
