# Generated by Django 2.2.10 on 2020-02-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-pk'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-pk'], 'verbose_name': 'Exchange rate', 'verbose_name_plural': 'Exchange rates'},
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('base', 'target')},
        ),
    ]
